ТЗ6: Доработана функциональность
kompot-I/java-kanban pull request #4
Opened 2024-04-20 08:40 UTC by kompot-I

2024-04-20 09:17 UTC, TomattmanYandex requested changes
Привет, хорошая работа, есть парочка комментариев в коде, посмотри как исправить их
+ Проверки не прошли, это надо исправить тоже

2024-04-20 09:17 UTC, TomattmanYandex commented on src/com/yandex/app/model/Node.java
> +    public E item;
делаем приватным все, и логика идет через геттеры и сеттеры
второй вариант, Node делаем внутренним классом в менеджере истории (и приватным) и тогда можно поля оставить публичными

2024-04-20 09:17 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryHistoryManager.java
> +    static Map<Integer, Node<Task>> history = new HashMap<>();
1)эта переменная не должна быть статической
2) модификатор доступа

2024-04-20 09:17 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryHistoryManager.java
> +            System.out.println(history);
выводить историю тут точно не надо

2024-04-20 09:17 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +        Set<Integer> idsSet = new HashSet<>();
такого метода по условию быть не должно

2024-04-20 09:17 UTC, TomattmanYandex commented on test/com/yandex/app/service/InMemoryHistoryManagerTest.java
> +    void taskInHistoryNotRepeat() {
по именованию тестовых методов
хорошо если они состоят из 2-3 частей
1) имя тестируемого метода
2) что должно произойти
3) при каких условиях (3 часть опциональна)
разделять их можно либо словами should и when или нижними плодчеркиваниями, для меня нижние подчеркивания лучше, так как проще воспринимаются
пример
add_tasksNotRepeat_addedTwoSameTasks

2024-04-20 09:34 UTC, kompot-I commented on src/com/yandex/app/model/Node.java
> +    public E item;
✅

2024-04-20 09:34 UTC, kompot-I commented on src/com/yandex/app/service/InMemoryHistoryManager.java
> +    static Map<Integer, Node<Task>> history = new HashMap<>();
✅

2024-04-20 09:34 UTC, kompot-I commented on src/com/yandex/app/service/InMemoryHistoryManager.java
> +            System.out.println(history);
✅

2024-04-20 09:38 UTC, kompot-I commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +        Set<Integer> idsSet = new HashSet<>();
Не очень согласен. У нас же есть методы по удалению всех тасков / сабтасков / эпиков или всего вместе. 
Реализация удаления происходит через id задач, чтобы было константное время. Соответственно нам нужно при удалении всех задач, передать их id's соответственно.

2024-04-20 09:41 UTC, kompot-I commented on test/com/yandex/app/service/InMemoryHistoryManagerTest.java
> +    void taskInHistoryNotRepeat() {
✅

2024-04-20 09:44 UTC, kompot-I commented
На счет проверок: Для разнообразия углубился в Mockito, чтобы тестируемый класс не затрагивал другие и для тестов использовалась обертка например Task(пустышка). 
Точно ли нужно переделывать это ?

2024-04-21 09:54 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +        Set<Integer> idsSet = new HashSet<>();
это было к тому, что по условию должны были быть методы на удаление всех тасков, сабтасков, эпиков но не сразу на полное очищение менеджера,
а если надо было бы полностью очищить историю, это можно сделать еще быстрее, ибо сейчас сложность будет n
а если очистить мапу, занулить head и tail то будет как раз таки константная сложность

2024-04-21 10:03 UTC, TomattmanYandex requested changes
Привет, пункт с новым методом не существенный, его можно оставить, все остальное хорошо, но вот сборка должна быть зеленой
ПО поводу твоего вопроса про mockito
обычно выделяют юнит тесты, и интеграционные
юнит - тестируют функционал конкретного метода, и для них удобно использовать mockito
интеграционные - тестируют взаимодействие между разными компонентами, с ними мокито используется гораздо реже
Хотя мокито также часто используют если есть какие ни  будь внешние зависимости, например нам нужно обращаться к какому то внешнему ресурсу, и для того чтобы при каждом вызове не дергать его, или чтобы отвязаться от его доступности в тестах тоже можно использовать мокито
по поводу пустышек не до конца понял (это снова про интеграцию) то зависит от сложности и в рамках текущего задания не уверен что надо

2024-04-22 13:57 UTC, TomattmanYandex approved these changes

2024-04-22 19:01 UTC, merged