Sprint 7 solution in file manager
kompot-I/java-kanban pull request #5
Opened 2024-05-09 09:59 UTC by kompot-I

2024-05-10 08:44 UTC, TomattmanYandex requested changes
Привет коментарии в коде, так же не хватает записи в файл историии, а так как историю пишем в файл, то также необходимо переопределить методы которые изменяют историю

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/model/Task.java
> +    public void setTaskType(TaskType taskType) {
я бы рекомендовал убрать этот метод, ведь используя его можно сказать что эпик это таск,
вместо сеттера, сделать переменную protected final TaskType taskType и как и сейчас проставлять в конструкторе нужное значение

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/model/Task.java
> +    public void setTaskType(TaskType taskType) {
ну или сделать сеттер protected
чтобы можно было вызвать только из классов наследников
(но первый вариант лучше)

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/service/ManagerFactory.java
> +    public static TaskManager getTaskManager() {
кажется по условию тут должен быть метод getDefault

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +    private final HistoryManager historyManager = ManagerFactory.getHistoryManager();
лучше вернуть, чтобы он как раньше передавался в конструкторе
так мы сможем создавать разные комбинации и этот класс не будет зависеть от реализации ManagerFactory

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +        this.file = file;
При создании должны считываться данные из файла

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +        this.file = file;
хороший вариант реализации это сделать этот конструктор приватным и позволять создавать объект только через метод loadFromFile

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +                        Epic epic = backManager.epicTasks.get(((Subtask) task).getEpicId());
я бы рекомендовал делать это отдельным циклом, после того как считается весь файл, потому что при текущей реализации, если мы прочитаем сабтаск до того как будет прочитан его эпик, эпик в конце останется без этого сабтаска

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +            }
история тоже должна быть считана из файла

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +    private static Task convertFromString(String line) {
Я бы рекомендовал создать отдельный класс TaskCsvConverter и закинуть методы на преобразование таска, сабтаск, эпика, истории в строку туда, и методы конвертации из троки тоже, так если появится новый тип храниния файлов, надо будет сделать нвоый класс конвертер с такими же методами но другой логикой, а тут только его подменить

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +    private String convertToString() {
тут то же тчо и выше, но я бы порекомндовал разбить этот метод на 3 с параметрами
чтобы преобразовывать один объект в строку

2024-05-10 08:44 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +    private String convertToString() {
а еще не хватает истории

2024-05-13 14:01 UTC, kompot-I commented
Привет. Надеюсь все учел, в ТЗ ничего про хранение истории в файле не было )

2024-05-13 19:49 UTC, TomattmanYandex requested changes
Привет, еще надо поправить парочку моментов

2024-05-13 19:49 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +            while (reader.ready()) {
два раза обходим файл , для того чтобы считать на втором цикле только историю, представь что в файле миллион строк, сколько времени они будет все проходить, ради одной строки

2024-05-13 19:49 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +            while (reader.ready()) {
можно добавить boolean переменную чтобы понимать была ли чистана строка разделяющая основной фал и историю, и от нее отталкиваться

2024-05-13 19:49 UTC, TomattmanYandex commented on src/com/yandex/app/service/FileBackedTaskManager.java
> +}
все еще не хватает переопределения методов получения по идентификатору, они изменяют историю измененная истария, значит надо перезаписывать в файл

2024-05-14 21:21 UTC, kompot-I commented
Писал в пачке на счет булевой переменной

2024-05-15 12:37 UTC, TomattmanYandex approved these changes
Принято
По поводу двух считываний
while (reader.ready()) { 
два раза, просто первый раз он читает только таски
второй раз игнорирует все кроме итсории

2024-05-24 10:12 UTC, merged