Sprint 8 solution time and duration
kompot-I/java-kanban pull request #6
Opened 2024-05-25 18:55 UTC by kompot-I

2024-05-25 21:09 UTC, TomattmanYandex requested changes
Привет, комменты в коде

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/model/Epic.java
> +        super(name, description, LocalDateTime.of(2024,5,25, 0, 0), 0);
почему если значение не установлено, то устанавливается какое то значение, кажется в условии  не было сказано, что это значение обязательно

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/model/Epic.java
> +        this.endTime = LocalDateTime.of(2024,5,25, 0, 0);
почему устанавливается какое то значение как время окончания?

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/model/Task.java
> +    public Task(String name, String description, LocalDateTime startTime, int duration) {
как создать таск, если я не хочу устанавливать ему время выполнения и время старта?

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/model/Task.java
> +        try {
лучше проверить что нужные значения установлены, и даже не пытаться что то делать если это не так

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +        if (timeOverlayValidator(task)) {
лучше избавиться от дополнительной вложенности
if(isOverlaped(task)){
return;
}
//основные действия

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +            setLifeTimeOfEpic(epic);
лучше как и updateEpicStatus(epic); назвать метод
updateEpicTimes например, тут очень бросается в глаза то, что имено в разных стилях

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
>          if (epic != null) {
тут кстати можно так же сделать, как написано выше, чтобы уменьшить вложенность
if(epic == null) {
retrun;
} 
//основные действия

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +        setLifeTimeOfEpic(epic);
зачем ему устанавливать время, если при добавлении его, у него нету сабтасков, а следовательно и времени никакого нету

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +            setLifeTimeOfEpic(epicTasks.get(subtask.getEpicId()));
про имя уже писал

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
>              updateEpicStatus(epic);
а пересчитать время эпикам

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +    private void setLifeTimeOfEpic(Epic epic) {
метод надо переименовать, писал выше

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +        for (Subtask sub : sublist) {
есть вариант 2, как это реализовать
сортируем тем же компаратором, время старта первого будет время старта эпика, время фниша последнего у которого есть время финиша - время финиша эпика, продолжительность сумма всех
(исправлять не обязательно, просто наблюдение

2024-05-25 21:09 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +    private boolean timeOverlayValidator(Task task) {
плохое имя метода, для класса было бы норм, методы это действия, и должны называться так же
напрмиер validateTimeOverlay но с таким именем, лучше было бы чтобы прокидывалось исключение
если хочешь возвращаемое значение, то
isTaskOverlaped или hasTimeInterseption

2024-05-27 08:13 UTC, TomattmanYandex requested changes
Привет, нашел еще парочку проблемных мест,
ну и добавил комментарии что можно еще улучшить

2024-05-27 08:13 UTC, TomattmanYandex commented on src/com/yandex/app/model/Task.java
> +    public Task(String name, String description, LocalDateTime startTime, int duration) {
это я считаю все еще актуальным, но оно не то чтобы очень важное

2024-05-27 08:13 UTC, TomattmanYandex commented on src/com/yandex/app/model/Task.java
> +        if (startTime != null && duration != null) {
обычно в начале проверяют сначала крайние значения, и если они не верны, то обрабатывают ошибочный вариант, а потом уже выполняют основные действия

делают так по нескольким причинам
1) уменьшает вложенность кода, основные действия на уровень ниже по вложенности
2) иногда неправильные данные можно исправить, и  продолжать обработку
3) часто логики больше при правильном выполнении, и таким образом получается что после модифицировать проще

2024-05-27 08:13 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
> +        if (epic == null) {
а где проверка на пересечение?

2024-05-27 08:13 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
>          if (tasks.containsKey(task.getId())) {
при обновлении тоже стоит проверять на пересечение, что если обновленнный таск содержит пересечения
да и с приоритезированными тасками стоит что то делать, ибо там таск не поменяется (точнее не всегда поменяется)
предлагаю написать три теста дополнительных
1) обновляем таск, делаем так чтобы он пересекался с другим таском, он не должен обновиться
2) обновляем таск без пересечений, смотрим что он обновился
3) обновляем таск без пересечений, но при обновлении не модифицируем старую переменную а создаем новый объект с нуля (чтобы у него была другая ссылка) и смотрим что он изменился в хранилище и в приоритезированных тасках

пример под последнее
Task task  = new Task("name", "description",...);
taskManager.createTask(task)

Task updatedTask = new Task(task.getName(), task.getDescription()...)//какие то поля стоит поменять чтобы понять, что таск не изменен (но не время и продолжительность)
updatedTask.setId(task.getId);//это признак того, что таск тот же

taskManaget.updateTask(updatedTask);

2024-05-27 08:13 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
>      public void updateSubtask(Subtask subtask) {
аналогично с предыдущим

2024-05-30 13:05 UTC, kompot-I commented on src/com/yandex/app/service/InMemoryTaskManager.java
>          if (tasks.containsKey(task.getId())) {
Надеюсь правильно понял, что для корректной работы TreeSet, мне нужно перед добавлением обновленной таски, удалять ее старую версию. Чтобы все корректно посчиталось и распределилось в сете.

2024-05-31 08:07 UTC, TomattmanYandex approved these changes
Принято

2024-05-31 08:07 UTC, TomattmanYandex commented on src/com/yandex/app/service/InMemoryTaskManager.java
>          if (tasks.containsKey(task.getId())) {
да, все правильно

2024-05-31 08:25 UTC, merged